l = Location.create(name: "New York")
l.recordings.create(temp: 32, status: "Sunny")
l.recordings.create(temp: 20, status: "Snow")
l.recordings.create(temp: 26, status: "Cloudy")
l.recordings.create(temp: 30, status: "Cloudy")
